[theme]
name=Mori

accent=#a7c080
text=#d3c6aa
textDim=#9da9a0
textMuted=#859289

logo=#a7c080
header=#7fbbb3
footer=#859289
help=#d3c6aa
link=#83c092
nowplaying=#dbbc7f
playbackstatus=#859289

playlist.rownum=#859289
playlist.title=#d3c6aa
playlist.playing=#a7c080

trackview.title=#d3c6aa
trackview.artist=#9da9a0
trackview.album=#9da9a0
trackview.year=#859289
trackview.time=#9da9a0
trackview.visualizer=#7fbbb3
trackview.lyrics=#d3c6aa

library.artist=#7fbbb3
library.album=#d3c6aa
library.track=#d3c6aa
library.enqueued=#859289
library.playing=#a7c080

search.label=#7fbbb3
search.query=#a7c080
search.result=#d3c6aa
search.enqueued=#859289
search.playing=#a7c080

progress.filled=#a7c080
progress.empty=#3d484d
progress.elapsed=#7fbbb3

status.info=#d3c6aa
status.warning=#dbbc7f
status.error=#e67e80
status.success=#a7c080
